# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'NewTest.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(841, 566)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 25, 841, 511))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.ScanButton = QtWidgets.QPushButton(self.tab)
        self.ScanButton.setGeometry(QtCore.QRect(20, 5, 131, 61))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.ScanButton.setFont(font)
        self.ScanButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.ScanButton.setCheckable(False)
        self.ScanButton.setChecked(False)
        self.ScanButton.setAutoRepeat(False)
        self.ScanButton.setAutoExclusive(False)
        self.ScanButton.setAutoRepeatDelay(300)
        self.ScanButton.setObjectName("pushButton")
        self.LinkButton = QtWidgets.QPushButton(self.tab)
        self.LinkButton.setGeometry(QtCore.QRect(360, 5, 131, 61))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.LinkButton.setFont(font)
        self.LinkButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.LinkButton.setObjectName("pushButton_2")
        self.DetectButton = QtWidgets.QPushButton(self.tab)
        self.DetectButton.setGeometry(QtCore.QRect(690, 5, 131, 61))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.DetectButton.setFont(font)
        self.DetectButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.DetectButton.setObjectName("pushButton_3")
        self.ScantableWidget = QtWidgets.QTableWidget(self.tab)
        self.ScantableWidget.setGeometry(QtCore.QRect(10, 80, 821, 321))
        self.ScantableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.ScantableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.ScantableWidget.setRowCount(255)
        self.ScantableWidget.setColumnCount(5)
        self.ScantableWidget.setObjectName("tableWidget")
        self.tabWidget.addTab(self.tab, "")
        self.ScantableWidget.setObjectName("tableWidget")
        self.progressBar = QtWidgets.QProgressBar(self.tab)
        self.progressBar.setGeometry(QtCore.QRect(10, 440, 821, 23))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(10, 410, 431, 20))
        self.label.setObjectName("label")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.ClearButton = QtWidgets.QPushButton(self.tab_2)
        self.ClearButton.setGeometry(QtCore.QRect(20, 5, 131, 61))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.ClearButton.setFont(font)
        self.ClearButton.setObjectName("pushButton_4")
        self.RecordTextBrowser = QtWidgets.QTextBrowser(self.tab_2)
        self.RecordTextBrowser.setGeometry(QtCore.QRect(10, 80, 821, 371))
        self.RecordTextBrowser.setObjectName("tableWidget_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 841, 26))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        self.stop_action = QtWidgets.QAction(MainWindow)
        self.stop_action.setObjectName("stop_action")
        self.exit_action = QtWidgets.QAction(MainWindow)
        self.exit_action.setObjectName("action_2")
        self.help_action = QtWidgets.QAction(MainWindow)
        self.help_action.setObjectName("action")
        self.menu.addAction(self.stop_action)
        self.menu.addAction(self.exit_action)
        self.menu_2.addAction(self.help_action)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())
        # self.deleteAction = QtWidgets.QAction('删除')
        # self.linkAction = QtWidgets.QAction('连接')
        # self.detectAction = QtWidgets.QAction('攻击')
        self.ScantableWidgetrightMenu = QtWidgets.QMenu(self.ScantableWidget)
        # self.ScantableWidgetrightMenu.addAction(self.deleteAction)
        # self.ScantableWidgetrightMenu.addAction(self.linkAction)
        # self.ScantableWidgetrightMenu.addAction(self.detectAction)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ETA-FINDER"))
        HorizontalHearder_1=['SSID','BSSID','RSSI','CH','ENC-AUTH']
        self.ScantableWidget.setHorizontalHeaderLabels(HorizontalHearder_1)
        for index in range(self.ScantableWidget.columnCount()):
            headItem = self.ScantableWidget.horizontalHeaderItem(index)
            headItem.setFont(QtGui.QFont("song", 12, QtGui.QFont.Bold))
            headItem.setForeground(QtGui.QBrush(QtCore.Qt.darkBlue))
            headItem.setTextAlignment(QtCore.Qt.AlignHCenter | QtCore.Qt.AlignVCenter)
        self.ScantableWidget.horizontalHeader().setSectionResizeMode(QtWidgets.QHeaderView.Stretch)
        self.ScantableWidget.setSortingEnabled(False)
        self.ScantableWidget.horizontalHeader().setSectionResizeMode(QtWidgets.QHeaderView.Stretch)
        self.ScantableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.ScantableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.ScantableWidget.setSelectionMode(QtWidgets.QTableWidget.ContiguousSelection)
        self.ScantableWidget.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.ScantableWidget.customContextMenuRequested.connect(self.whetherShow)
        self.label.setText(_translate("Dialog", "Click the Scan button to start!"))
        self.ScanButton.setText(_translate("MainWindow", "Scan"))
        self.LinkButton.setText(_translate("MainWindow", "Connect"))
        self.DetectButton.setText(_translate("MainWindow", "Detect"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Function"))
        self.ClearButton.setText(_translate("MainWindow", "Clear"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Detection"))
        self.menu.setTitle(_translate("MainWindow", "Menu"))
        self.menu_2.setTitle(_translate("MainWindow", "Help"))
        self.stop_action.setText(_translate("MainWindow", "Stop"))
        self.exit_action.setText(_translate("MainWindow", "Exit"))
        self.help_action.setText(_translate("MainWindow", "Help"))

    def whetherShow(self,pos):

        item = self.ScantableWidget.itemAt(pos)
        if item != None:
            self.rightMenuShow()

    def rightMenuShow(self):

        self.ScantableWidgetrightMenu.exec_(QtGui.QCursor.pos())
